services:
  YesPlayMusic:
    build:
      context: .
    image: yesplaymusic
    container_name: 独听者
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 80:80
    restart: always
